name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run Tests
        # We set the PYTHONPATH here so pytest can find your scheduler.py
        env:
          PYTHONPATH: .
        run: pytest